package domain

import (
	"math/big"

	"github.com/ethereum/go-ethereum/core/types"
)

// Events types copied from sc bindings codegen autogenerated file
// DO NOT EDIT

// VeboValidatorExitRequest represents a ValidatorExitRequest event raised by the Vebo contract.
type VeboValidatorExitRequest struct {
	StakingModuleId *big.Int
	NodeOperatorId  *big.Int
	ValidatorIndex  *big.Int
	ValidatorPubkey []byte
	Timestamp       *big.Int
	Raw             types.Log // Blockchain specific contextual infos
}
